/**
 * TextureManager.ts
 * Manages local texture assets and fallback mapping for the 3D environment.
 * Prevents CORS errors by serving local SVG patterns instead of external URLs.
 */

// Available local textures (generated by scripts/generate-textures.js)
const LOCAL_TEXTURES = {
    WOOD: '/textures/wood.svg',
    CONCRETE: '/textures/concrete.svg',
    TILE: '/textures/tile.svg',
    FABRIC: '/textures/fabric.svg',
    GRID: '/textures/grid.svg',
    // [NEW] 추가 텍스처
    METAL: '/textures/metal.svg',
    MARBLE: '/textures/marble.svg',
    GRASS: '/textures/grass.svg',
    SAND: '/textures/sand.svg',
};

import { findTextureByKeyword } from '@/data/texture_library';

export class TextureManager {
    /**
     * Maps a semantic keyword or specific URL to a safe local texture path.
     * @param description A texture URL, material name, or description (e.g., "dark oak wood")
     * @returns Absolute path to a local texture asset or Remote URL
     */
    static getTexturePath(description: string = ""): string {
        const lowerDesc = description.toLowerCase();

        // [NEW] 1. Check Remote Texture Library (High Quality PBR)
        const remoteTex = findTextureByKeyword(lowerDesc);
        if (remoteTex) {
            // Return color map for now (RoomGenerator uses map only)
            // Ideally we should return the whole PBR set, but existing code expects a string path
            return remoteTex.maps.color;
        }

        // [하드코딩 제거] 키워드 기반 로컬 텍스처 하드코딩 매핑 전면 금지.
        // 시맨틱 검색에서 실패할 경우 오직 기본 기본값(GRID) 하나만 반환합니다.
        return LOCAL_TEXTURES.GRID;
    }

    static getTextureTint(description: string = ""): string {
        // [하드코딩 제거] 특정 키워드에 따른 틴트 색상 강제 지정 룰 전면 금지.
        // 모든 베이스 틴트는 기본값 화이트로 처리하여 본연의 텍스처/재질 색상을 존중합니다.
        return '#ffffff';
    }
}
