/**
 * TextureManager.ts
 * Manages local texture assets and fallback mapping for the 3D environment.
 * Prevents CORS errors by serving local SVG patterns instead of external URLs.
 */

// Available local textures (generated by scripts/generate-textures.js)
const LOCAL_TEXTURES = {
    WOOD: '/textures/wood.svg',
    CONCRETE: '/textures/concrete.svg',
    TILE: '/textures/tile.svg',
    FABRIC: '/textures/fabric.svg',
    GRID: '/textures/grid.svg',
    // [NEW] 추가 텍스처
    METAL: '/textures/metal.svg',
    MARBLE: '/textures/marble.svg',
    GRASS: '/textures/grass.svg',
    SAND: '/textures/sand.svg',
};

import { findTextureByKeyword } from '@/data/texture_library';

export class TextureManager {
    /**
     * Maps a semantic keyword or specific URL to a safe local texture path.
     * @param description A texture URL, material name, or description (e.g., "dark oak wood")
     * @returns Absolute path to a local texture asset or Remote URL
     */
    static getTexturePath(description: string = ""): string {
        const lowerDesc = description.toLowerCase();

        // [NEW] 1. Check Remote Texture Library (High Quality PBR)
        const remoteTex = findTextureByKeyword(lowerDesc);
        if (remoteTex) {
            // Return color map for now (RoomGenerator uses map only)
            // Ideally we should return the whole PBR set, but existing code expects a string path
            return remoteTex.maps.color;
        }

        // [NEW] 금속 계열
        if (lowerDesc.includes('metal') || lowerDesc.includes('steel') || lowerDesc.includes('chrome') || lowerDesc.includes('iron') || lowerDesc.includes('금속') || lowerDesc.includes('철')) {
            return LOCAL_TEXTURES.METAL;
        }
        // [NEW] 대리석/고급 계열
        if (lowerDesc.includes('marble') || lowerDesc.includes('luxury') || lowerDesc.includes('대리석')) {
            return LOCAL_TEXTURES.MARBLE;
        }
        // [NEW] 잔디/자연 계열
        if (lowerDesc.includes('grass') || lowerDesc.includes('lawn') || lowerDesc.includes('잔디') || lowerDesc.includes('풀밭')) {
            return LOCAL_TEXTURES.GRASS;
        }
        // [NEW] 모래 계열
        if (lowerDesc.includes('sand') || lowerDesc.includes('desert') || lowerDesc.includes('beach') || lowerDesc.includes('모래') || lowerDesc.includes('사막') || lowerDesc.includes('해변')) {
            return LOCAL_TEXTURES.SAND;
        }

        // 기존 매핑
        // Bilingual & Theme Mapping
        if (lowerDesc.includes('wood') || lowerDesc.includes('plank') || lowerDesc.includes('oak') || lowerDesc.includes('floor') || lowerDesc.includes('나무') || lowerDesc.includes('바닥')) {
            return LOCAL_TEXTURES.WOOD;
        }
        if (lowerDesc.includes('concrete') || lowerDesc.includes('cement') || lowerDesc.includes('grey') || lowerDesc.includes('stone') || lowerDesc.includes('brick') || lowerDesc.includes('medieval') || lowerDesc.includes('돌') || lowerDesc.includes('벽돌') || lowerDesc.includes('성벽')) {
            return LOCAL_TEXTURES.CONCRETE;
        }
        if (lowerDesc.includes('tile') || lowerDesc.includes('gold') || lowerDesc.includes('royal') || lowerDesc.includes('고급') || lowerDesc.includes('황금')) {
            return LOCAL_TEXTURES.TILE;
        }
        if (lowerDesc.includes('fabric') || lowerDesc.includes('carpet') || lowerDesc.includes('rug') || lowerDesc.includes('cloth') || lowerDesc.includes('천') || lowerDesc.includes('카펫')) {
            return LOCAL_TEXTURES.FABRIC;
        }
        if (lowerDesc.includes('magic') || lowerDesc.includes('glowing') || lowerDesc.includes('mystic') || lowerDesc.includes('마법') || lowerDesc.includes('신비')) {
            return LOCAL_TEXTURES.TILE; // Tile looks more "finished" for magic
        }

        return LOCAL_TEXTURES.GRID;
    }

    static getTextureTint(description: string = ""): string {
        const lowerDesc = description.toLowerCase();

        // Specific Theme Tints
        if (lowerDesc.includes('dark') || lowerDesc.includes('night')) return '#222222';
        if (lowerDesc.includes('magic') || lowerDesc.includes('신비')) return '#4488ff'; // Arcane blue
        if (lowerDesc.includes('luxury') || lowerDesc.includes('royal') || lowerDesc.includes('고급') || lowerDesc.includes('gold')) return '#ffd700'; // Gold
        if (lowerDesc.includes('nature') || lowerDesc.includes('forest') || lowerDesc.includes('숲')) return '#228b22'; // Forest Green
        if (lowerDesc.includes('warm') || lowerDesc.includes('home')) return '#ccaa88'; // Warm beige
        if (lowerDesc.includes('blood') || lowerDesc.includes('horror') || lowerDesc.includes('피')) return '#880000'; // Dark Red

        // Base color fallbacks
        if (lowerDesc.includes('wood') || lowerDesc.includes('나무')) return '#8b4513';
        if (lowerDesc.includes('stone') || lowerDesc.includes('돌')) return '#808080';

        return '#ffffff';
    }
}
